tools: Fix compilation error
Fixed ERROR: File tools/dumptool/clients/__init__.py
does not exist by removing the inclusions in meson.build

Signed-off-by: Krishna Pamnani <krishna.pamnani@ibm.com>